[package]
name = "reimtris2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rodio = "0.20.1"
serde = { version = "1.0.218", features = ["serde_derive"] }
toml = "0.8.20"
xdg = "2.5.2"

[dependencies.sdl2]
version = "0.37.0"
features = ["ttf"]
